import Slider from "@/components/homepage/slider";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <Slider />
    </>
  );
}
