import PageHeader from '@/components/common/page-header';
import React from 'react'

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};
const LoginPage = () => {
  return (
    <
      
    >
    <PageHeader/>
      Login Page
    </>
  )
}

export default LoginPage
