import PageHeader from '@/components/common/page-header'
import { wait } from '@/utils/misc'
import React from 'react'

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
const Contact = async() => {
  await wait(5000)
  return (
    <div>
      <PageHeader title="Contact" />
      
    </div>
  )
}

export default Contact
