import PageHeader from '@/components/common/page-header'
import React from 'react'

export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};
const ProductsPage = () => {
  return (
    <div>
      <PageHeader title="Products" />
      ProductsPage
    </div>
  )
}

export default ProductsPage
