import DashboardHeader from "@/components/dashboard/header";
import Link from "next/link";
import React from "react";
import { Container } from "react-bootstrap";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashboardLayout = ({ children }) => {
  return (
    <>
    <DashboardHeader/>
      <Container className="flex-grow-1">

      {children}
      </Container>
    </>
  );
};

export default DashboardLayout;
