import PageHeader from '@/components/common/page-header'
import React from 'react'

export const metadata = {
  title:{
    absolute:"free title"
  },
  description: "Generated by create next app",
};
const ProductDetails = ({params}) => {
  return (
    <div>
      <PageHeader title="ABc" />
    ProductDetails: {params.id}
    </div>
  )
}

export default ProductDetails
